name: CI / CD Pipeline - go-validate-cpf

on:
  push:
    branches:
      - main

  pull_request:
    types:
      - opened
      - reopened
      - closed
      - synchronize
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.19", "1.20", "1.21.x", "1.22"]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Verify dependencies
        run: go mod verify

      - name: Run build
        run: go build -v ./...

      - name: Run tests with coverage
        run: go test -v ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...

      - name: Check test coverage
        uses: vladopajic/go-test-coverage@v2
        with:
            config: ./.test_coverage.yml
            
  osv-scan:
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@v1.6.2-beta1"
    with:
      scan-args: |-
        --lockfile=./../../go.mod
    permissions:
      security-events: write
      contents: read

